spring:
  datasource:
    url: jdbc:mysql://bj-cdb-reoya5p4.sql.tencentcdb.com:63488/bim-dev?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=GMT%2B8
    username: mdbim
    password: md9007md3389md
mybatis:
  mapper-locations: classpath:mapping/*.xml
  #type-aliases-package: cn.com.lrh.export.structure.entity
 
#showSql
logging:
  level:
     cn.com.lrh.export.structure.mapper : debug