spring:
  datasource:
    url: XXXXX
    username: XXXX
    password: XXXXX
mybatis:
  mapper-locations: classpath:mapping/*.xml
  #type-aliases-package: cn.com.lrh.export.structure.entity
 
#showSql
logging:
  level:
     cn.com.lrh.export.structure.mapper : debug